# Staroid uses skaffold to build container images and deploy Kubernetes manifests.
apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: object-detection
    context: .
    docker:
      dockerfile: .staroid/Dockerfile_object-detection
  - image: text-sentiment
    context: .
    docker:
      dockerfile: .staroid/Dockerfile_text-sentiment
deploy:
  kubectl:
    manifests:
      - .staroid/k8s/ml-backend.yaml
      - .staroid/k8s/ml-backend-object-detection.yaml
      - .staroid/k8s/ml-backend-text-sentiment.yaml
      - .staroid/k8s/labelstudio.yaml
profiles:
  - name: minikube
    patches:
      - op: add
        path: /deploy/kubectl/manifests/0
        value: .staroid/k8s/minikube.yaml
