# Kubernetes manifests for label studio
apiVersion: apps/v1
kind: Deployment
metadata:
  name: labelstudio-deployment
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: labelstudio
  template:
    metadata:
      labels:
        app: labelstudio
    spec:
      serviceAccountName: root
      containers:
      - name: labelstudio
        image: heartexlabs/label-studio:0.9.0
        ports:
        - name: service-port
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /version
            port: service-port
          failureThreshold: 20
          periodSeconds: 2
        volumeMounts:
          - name: project-vol
            mountPath: /my_project
      volumes:
        - name: project-vol
          persistentVolumeClaim:
            claimName: project-volume
---
kind: Service
apiVersion: v1
metadata:
  name: label-studio
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: labelstudio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-volume
  annotations:
    storage.staroid.com/scope: Instance
    storage.staroid.com/file-manager: "0:0"
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
