# Defines resources required to run on minikube
apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: ./project-pv
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: k8s.io/minikube-hostpath
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: root
