# Kubernetes manifests for label studio
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: object-detection
  template:
    metadata:
      labels:
        app: ml-backend
        pod.staroid.com/isolation: dedicated
        pod.staroid.com/instance-type: standard-4
        pod.staroid.com/spot: "false"
    spec:
      serviceAccountName: root
      containers:
      - name: object-detection
        image: object-detection
        command:
        - "bash"
        - "-c"
        - >-
          cd /work &&
          label-studio-ml start coco-detector --with
          config_file=/work/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py
          checkpoint_file=/work/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
          score_threshold=${SCORE_THRESHOLD}
          project_full_path=/label-studio/my_project
          device=$( echo "$DEVICE" | grep gpu > /dev/null && echo "gpu:0" || echo "cpu")
        env:
        - name: SCORE_THRESHOLD
          value: "0.5"
        - name: DEVICE
          value: "standard-4"
        volumeMounts:
          - name: project-vol
            mountPath: /label-studio/my_project
      volumes:
        - name: project-vol
          persistentVolumeClaim:
            claimName: project-volume
