# Kubernetes manifests for label studio
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-sentiment
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: text-sentiment
  template:
    metadata:
      labels:
        app: ml-backend
    spec:
      serviceAccountName: root
      containers:
      - name: text-sentiment
        image: text-sentiment
